# 테스트용 docker-compose - 모든 메트릭 수집 가능, AWS 배포용이 아닙니다

services:
  starbucks-backend:
    build:
      context: .
      dockerfile: Dockerfile-test
    container_name: starbucks-backend

    # 메모리 제한 추가 (JVM -Xmx1024m + 시스템 오버헤드 고려하여 2GB 설정)
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/starbucks
      SPRING_DATASOURCE_USERNAME: starbucks
      SPRING_DATASOURCE_PASSWORD: starbucks123!
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: true
      # AWS EC2 t3.small에 맞도록 JVM 메모리 크기 설정 (Heap: 1GB + NonHeap 제한)
      JAVA_OPTS: "-Xmx1024m -Xms256m -XX:+UseG1GC -XX:MaxMetaspaceSize=256m -XX:ReservedCodeCacheSize=128m -XX:MaxDirectMemorySize=128m"

    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # 헬스체크 추가
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
