server:
  port: 8080
  servlet:
    context-path: /api/${api.version}
  forward-headers-strategy: framework
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 400
      min-spare: 20
    max-connections: 10000
    accept-count: 200
    connection-timeout: 20000

api:
  version: v1

spring:
  profiles:
    active: dev
  application:
    name: git-kkalnane-starbucks

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    metrics:
      cache:
        time-to-live: 30s
  metrics:
    tags:
      application: ${spring.application.name}

# PayCard 설정
pay-card:
  init-amount: 500000