@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}/api/v1


### 모든 음료(커피 포함) 목록을 조회합니다.
GET {{baseUrl}}/items/drinks?page=0

### 페이지네이션 없이 모든 디저트 목록을 조회합니다.
GET {{baseUrl}}/items/desserts
