@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}/api/v1


### 모든 음료(커피 포함) 목록을 조회합니다.
GET {{baseUrl}}/items/drinks?page=0

### 음료의 ID 값을 이용해 단일 음료를 조회합니다.
GET {{baseUrl}}/items/drinks/101

### 음료의 ID 값을 이용해 옵션이 존재하는 단일 음료를 조회합니다.
GET {{baseUrl}}/items/drinks/104

### 페이지네이션 없이 모든 디저트 목록을 조회합니다.
GET {{baseUrl}}/items/desserts
