@host = localhost
@port = 8080
@baseUrl = http://{{host}}:{{port}}/api/v1
### ========================================
### 주문 생성 테스트
### ========================================

### 로그인하고 인증 토큰(JWT) 발급받기
POST {{baseUrl}}/merchant/signup
Content-Type: application/json

{
  "name": "폴바셋",
  "email": "starbucks10@gmail.com",
  "password": "Test1234!!"
}


### 로그인하고 인증 토큰(JWT) 발급받기
POST {{baseUrl}}/merchant/auth/login
Content-Type: application/json

{

  "email": "starbucks10@corp.com",
  "password": "Test1234!!"
}